-- MySQL Script generated by MySQL Workbench
-- Fri Mar 31 16:41:01 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema labs_pgt
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema labs_pgt
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `labs_pgt` DEFAULT CHARACTER SET utf8 ;
USE `labs_pgt` ;

-- -----------------------------------------------------
-- Table `labs_pgt`.`conta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labs_pgt`.`conta` ;

CREATE TABLE IF NOT EXISTS `labs_pgt`.`conta` (
  `conta_id` INT NOT NULL,
  `conta_email` VARCHAR(45) NOT NULL,
  `conta_nome` VARCHAR(90) NOT NULL,
  `conta_senha` VARCHAR(45) NOT NULL,
  `conta_supervisor` TINYINT NOT NULL,
  PRIMARY KEY (`conta_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labs_pgt`.`pgt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labs_pgt`.`pgt` ;

CREATE TABLE IF NOT EXISTS `labs_pgt`.`pgt` (
  `pgt_id` INT NOT NULL,
  `pgt_titulo` VARCHAR(90) NOT NULL,
  `pgt_status` VARCHAR(9) NOT NULL,
  `pgt_data_criacao` DATETIME NOT NULL,
  `pgt_tipo` VARCHAR(4) NOT NULL,
  `pgt_nota_qual` DECIMAL NULL,
  `pgt_nota_def` DECIMAL NULL,
  PRIMARY KEY (`pgt_id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labs_pgt`.`conta_pgt`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labs_pgt`.`conta_pgt` ;

CREATE TABLE IF NOT EXISTS `labs_pgt`.`conta_pgt` (
  `conta_pgt_id` INT NOT NULL,
  `pgt_id` INT NOT NULL,
  `conta_id` INT NOT NULL,
  `conta_pgt_funcao` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`conta_pgt_id`),
  INDEX `conta_pgt_conta_idx` (`conta_id` ASC),
  INDEX `conta_pgt_pgt_idx` (`pgt_id` ASC),
  CONSTRAINT `conta_pgt_conta`
    FOREIGN KEY (`conta_id`)
    REFERENCES `labs_pgt`.`conta` (`conta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `conta_pgt_pgt`
    FOREIGN KEY (`pgt_id`)
    REFERENCES `labs_pgt`.`pgt` (`pgt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labs_pgt`.`etapa`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labs_pgt`.`etapa` ;

CREATE TABLE IF NOT EXISTS `labs_pgt`.`etapa` (
  `etapa_id` INT NOT NULL,
  `etapa_descricao` MEDIUMTEXT NOT NULL,
  `etapa_feedback` MEDIUMTEXT NULL,
  `etapa_data_criacao` DATETIME NOT NULL,
  `etapa_pgt_id` INT NOT NULL,
  PRIMARY KEY (`etapa_id`),
  INDEX `etapa_pgt_idx` (`etapa_pgt_id` ASC),
  CONSTRAINT `etapa_pgt`
    FOREIGN KEY (`etapa_pgt_id`)
    REFERENCES `labs_pgt`.`pgt` (`pgt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labs_pgt`.`cronograma`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labs_pgt`.`cronograma` ;

CREATE TABLE IF NOT EXISTS `labs_pgt`.`cronograma` (
  `cronograma_id` INT NOT NULL,
  `cronograma_data` DATETIME NOT NULL,
  `cronograma_titulo` VARCHAR(45) NOT NULL,
  `cronograma_descr` MEDIUMTEXT NULL,
  `cronograma_tipo` VARCHAR(12) NOT NULL,
  `cronograma_pgt_id` INT NOT NULL,
  PRIMARY KEY (`cronograma_id`),
  INDEX `cronograma_pgt_idx` (`cronograma_pgt_id` ASC),
  CONSTRAINT `cronograma_pgt`
    FOREIGN KEY (`cronograma_pgt_id`)
    REFERENCES `labs_pgt`.`pgt` (`pgt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `labs_pgt`.`formularios`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `labs_pgt`.`formularios` ;

CREATE TABLE IF NOT EXISTS `labs_pgt`.`formularios` (
  `formulario_id` INT NOT NULL,
  `formulario_tipo` VARCHAR(12) NOT NULL,
  `formulario_nota_1` DECIMAL NULL,
  `formulario_nota_2` DECIMAL NULL,
  `formulario_nota_3` DECIMAL NULL,
  `formulario_nota_4` DECIMAL NULL,
  `formulario_nota_5` DECIMAL NULL,
  `formulario_nota_6` DECIMAL NULL,
  `formulario_comentario_1` MEDIUMTEXT NULL,
  `formulario_comentario_2` MEDIUMTEXT NULL,
  `formulario_comentario_3` MEDIUMTEXT NULL,
  `formulario_comentario_4` MEDIUMTEXT NULL,
  `formulario_comentario_5` MEDIUMTEXT NULL,
  `formulario_comentario_6` MEDIUMTEXT NULL,
  `formulario_pgt_id` INT NOT NULL,
  `formulario_conta_autor` INT NOT NULL,
  PRIMARY KEY (`formulario_id`),
  INDEX `formulario_pgt_idx` (`formulario_pgt_id` ASC),
  INDEX `formulario_conta_autor_idx` (`formulario_conta_autor` ASC),
  CONSTRAINT `formulario_pgt`
    FOREIGN KEY (`formulario_pgt_id`)
    REFERENCES `labs_pgt`.`pgt` (`pgt_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `formulario_conta_autor`
    FOREIGN KEY (`formulario_conta_autor`)
    REFERENCES `labs_pgt`.`conta` (`conta_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
